[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  command = 'npm run build'
  functions = 'functions'
  publish = 'dist'
  included_files = ["src/assets/**"]
[dev]
  targetPort = 5173
  framework = "vite"
  command = "npm run dev:vite"